### ISSUE TITLE
4.1.0 Alpha2版本的autojs，无法启动项目

### ISSUE THREAD

**Issue by kuma-100** [Nick-Hopps/Arkknights_autoscript#1]
运行项目报未打开无障碍服务，实际已打开
报错信息如下：
Auto.js：错误：Error：未打开无障碍服务（file://storage/emulated/0/脚本/Arkknights_autoscript/lib/Automator.js#33)

**Comment by Nick-Hopps** [comment]
先完全退出再打开软件，然后再重新打开一下无障碍服务，再试试。

如果还不行，新建一个文件，运行

toastLog(auto.service);

看看有没有输出

**Comment by kuma-100** [comment]
log提示：Auto.js：undefined

**Comment by Nick-Hopps** [comment]
那就换成 4.1.1 版本看看，免费版最新是 4.1.1 Alpha2

**Comment by kuma-100** [comment]
用4.1.1版本可以
