### ISSUE TITLE
[error] TypeError: Cannot find function pool .. 直接调用ak.start()出错 

### ISSUE THREAD

**Issue by ryuujo1573** [Nick-Hopps/Arkknights_autoscript#2]
![Screenshot_2021-09-23-13-02-45-455_org autojs aut](https://user-images.githubusercontent.com/16525512/134457046-493f74b1-f346-48ed-9ffb-a8789ebab818.jpg)
我的操作顺序，

- 打开1-7（屏幕上已显示右下角开始行动）
- 使用MIUI弹窗打开Auto.js
- 运行launch.js（修改了最后部分if的判断，直接调用ak.start()。）

开始行动被点击，进入下一层界面后停止并报错，如图

**Comment by Nick-Hopps** [comment]
你的 Autojs 版本号是多少？



---原始邮件---
发件人: "Ryuujo ***@***.***&gt;
发送时间: 2021年9月23日(周四) 中午1:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Nick-Hopps/Arkknights_autoscript] [error] TypeError: Cannot find function pool .. 直接调用ak.start()出错  (#2)




 

 我的操作顺序，
  
打开1-7（屏幕上已显示右下角开始行动） 

使用MIUI弹窗打开Auto.js 

运行launch.js（修改了最后部分if的判断，直接调用ak.start()。） 
 
开始行动被点击，进入下一层界面后停止并报错，如图

**Comment by ryuujo1573** [comment]
Version 4.1.1 Alpha2

**Comment by Nick-Hopps** [comment]
看起来应该是4.1.1没有提供线程池的接口，需要写一个接口做兼容😅



---原始邮件---
发件人: "Ryuujo ***@***.***&gt;
发送时间: 2021年9月23日(周四) 中午1:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nick-Hopps/Arkknights_autoscript] [error] TypeError: Cannot find function pool .. 直接调用ak.start()出错  (#2)




 Version 4.1.1 Alpha2

**Comment by ryuujo1573** [comment]
辛苦啦！感谢您！！
