### ISSUE TITLE
大佬为什么进入游戏后就自动点退出

### ISSUE THREAD

**Issue by DaewooYou** [Nick-Hopps/Arkknights_autoscript#4]
进入后就点退出，也不走流程，用的雷电模拟器，问题出现在人机认证后，进入就直接关闭游戏

**Comment by Nick-Hopps** [comment]
脚本已经很久没开发了，已经不推荐使用了，推荐使用社区开发的 [MAA](https://maa.plus)，我自己现在也用这个。
